subscribers:
 - name: "teleop_keyboard"
   topic: "input/teleop_cmd_vel"
   timeout: 0.2
   priority: 0

- name: "default"
  topic: "input/default"
  timeout: 0.2
  priority: 1

publisher: "output/cmd_vel_mux":
